base_config: configs/tts/fs2.yaml
data_dir: 'data/ljspeech'
raw_data_dir: 'data/raw/LJSpeech-1.1'

# model
dropout: 0.2
max_tokens: 28000
val_check_interval: 1000

noise_factor: 1.0

reference_encoder_filters: "32 32 64 64 128 128"

